version: "3.7"

volumes:
  db-volume:
    name: "${NODE_ENV}-db-volume"
networks:
  app-network:
    name: "${NODE_ENV}-network"
services:
  backend:
    build:
      context: ./backend
      target: ${NODE_ENV}
    restart: unless-stopped
    working_dir: /usr/src/app
    depends_on: 
      - db
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    networks:
      - app-network
  app:
    build:
      context: ./frontend
      target: ${NODE_ENV}
    ports:
      - ${APP_PORT}:3000
    depends_on: 
        - backend
    environment:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_BANKAPI_URL: ${NEXT_PUBLIC_BANKAPI_URL}
        BANKAPI_URL: ${BANKAPI_URL}
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - app-network
   
       