version: "3.7"

services:
  backend:
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules/
  app:
    volumes:
        - ./frontend:/app
        - /app/node_modules/
        - /app/.next/
    networks:
      - app-network

 
  