version: "3.7"

volumes:
  db-volume:
    name: "${NODE_ENV}-db-volume"
networks:
  app-network:
    name: "${NODE_ENV}-network"
services:
  backend:
    build:
      context: ./backend
      target: ${NODE_ENV}
    restart: unless-stopped
    working_dir: /usr/src/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${APP_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    networks:
      - app-network
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PORT: ${DB_PORT}
    networks:
      - app-network
   
       